### ISSUE TITLE
Assert error: assert(primitive_size <= 512)

### ISSUE THREAD

**Issue by hzxie** [Colin97/MSN-Point-Cloud-Completion#2]
I got the following errors when setting `n_pts` to `16384`.

```
Namespace(batchSize=16, env='MSN_TRAIN', model='', n_primitives=16, nepoch=25, num_points=16384, workers=24)
Random Seed:  3764
Train Set Size:  28974
Traceback (most recent call last):
  File "train.py", line 121, in <module>
    output1, output2, emd1, emd2, expansion_penalty  = network(input, gt.contiguous(), 0.005, 50)         
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 38, in forward
    output1, output2, expansion_penalty = self.model(inputs)
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/xiehaozhe/Development/MSN-Point-Cloud-Completion/model.py", line 159, in forward
    dist, _, mean_mst_dis = self.expansion(out1, self.num_points//self.n_primitives, 1.5)
  File "/mnt/lustre/xiehaozhe/Applications/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./expansion_penalty/expansion_penalty_module.py", line 53, in forward
    return expansionPenaltyFunction.apply(input, primitive_size, alpha)
  File "./expansion_penalty/expansion_penalty_module.py", line 27, in forward
    assert(primitive_size <= 512)
AssertionError
```

**Comment by hzxie** [comment]
I changed the `n_primitives` to `32` to solve this problem.
Is it correct?

**Comment by Colin97** [comment]
Yes, you are right.

**Comment by hzxie** [comment]
Thank you very much.
