### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by superxiaoying** [Colin97/MSN-Point-Cloud-Completion#20]
Hi,
Thanks for your great work.
When I train the model, here are some logs about connection refused, just as the following Traceback shown.
But the model in training ... , do I need care the connection logs?

Best and Thanks

#####

Traceback (most recent call last):
  File "/home/yjcai/anaconda3/envs/msn/lib/python3.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/yjcai/anaconda3/envs/msn/lib/python3.7/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/yjcai/anaconda3/envs/msn/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/yjcai/anaconda3/envs/msn/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yjcai/anaconda3/envs/msn/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/yjcai/anaconda3/envs/msn/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
 object at 0x7f1a8f4b1ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
MSN_TRAIN train [0: 0/9]  emd1: 0.341410 emd2: 0.302342 expansion_penalty: 0.003462
MSN_TRAIN train [0: 1/9]  emd1: 0.321795 emd2: 0.290033 expansion_penalty: 0.003422
MSN_TRAIN train [0: 2/9]  emd1: 0.347615 emd2: 0.314816 expansion_penalty: 0.003539
MSN_TRAIN train [0: 3/9]  emd1: 0.331207 emd2: 0.294323 expansion_penalty: 0.003690
MSN_TRAIN train [0: 4/9]  emd1: 0.306453 emd2: 0.276825 expansion_penalty: 0.003754
MSN_TRAIN train [0: 5/9]  emd1: 0.277850 emd2: 0.246808 expansion_penalty: 0.003884
MSN_TRAIN train [0: 6/9]  emd1: 0.303935 emd2: 0.266290 expansion_penalty: 0.003877
MSN_TRAIN train [0: 7/9]  emd1: 0.293241 emd2: 0.256959 expansion_penalty: 0.004172
MSN_TRAIN train [0: 8/9]  emd1: 0.285149 emd2: 0.239006 expansion_penalty: 0.004101
MSN_TRAIN train [0: 9/9]  emd1: 0.309674 emd2: 0.286977 expansion_penalty: 0.004666

**Comment by Colin97** [comment]
It's about visdom. If you do not utilize it to visualize the results, you can ignore it.
